list(APPEND CMAKE_MODULE_PATH "./tools/adb")
find_package(Graphviz)
if(GRAPHVIZ_FOUND)
	message("libgraphviz found, visualization enabled")
	set(GRAPHVIZ_FLAG "-DWITH_GRAPHVIZ")
else(GRAPHVIZ_FOUND)
	message("libgraphviz not found, visualization disabled")
	set(GRAPHVIZ_FLAG "")
endif(GRAPHVIZ_FOUND)
set(TYPE binary)
set(LOCAL_CFLAGS "-DDEBUGGER ${GRAPHVIZ_FLAG} ${GRAPHVIZ_COMPILE_FLAGS}")
set(LOCAL_LIBS adam_dbg readline ${GRAPHVIZ_LIBRARIES})
