#ifndef __DALVIK_TOKENS_H__
#define __DALVIK_TOKENS_H__

#define DALVIK_MAX_NUM_KEYWORDS 256

extern const char* dalvik_keywords[DALVIK_MAX_NUM_KEYWORDS];

#define DALVIK_TOKEN_MOVE       (dalvik_keywords[0])
#define DALVIK_TOKEN_RETURN     (dalvik_keywords[1])
#define DALVIK_TOKEN_CONST      (dalvik_keywords[2])
#define DALVIK_TOKEN_MONITOR    (dalvik_keywords[3])
#define DALVIK_TOKEN_CHECK      (dalvik_keywords[4])
#define DALVIK_TOKEN_INSTANCE   (dalvik_keywords[5])
#define DALVIK_TOKEN_ARRAY      (dalvik_keywords[6])
#define DALVIK_TOKEN_NEW        (dalvik_keywords[7])
#define DALVIK_TOKEN_FILLED     (dalvik_keywords[8])
#define DALVIK_TOKEN_16         (dalvik_keywords[9])
#define DALVIK_TOKEN_FROM16     (dalvik_keywords[10])
#define DALVIK_TOKEN_WIDE       (dalvik_keywords[11])
#define DALVIK_TOKEN_OBJECT     (dalvik_keywords[12])
#define DALVIK_TOKEN_RESULT     (dalvik_keywords[13])
#define DALVIK_TOKEN_EXCEPTION  (dalvik_keywords[14])
#define DALVIK_TOKEN_VOID       (dalvik_keywords[15])
#define DALVIK_TOKEN_4          (dalvik_keywords[16])
#define DALVIK_TOKEN_HIGH16     (dalvik_keywords[17])
#define DALVIK_TOKEN_32         (dalvik_keywords[18])
#define DALVIK_TOKEN_CLASS      (dalvik_keywords[19])
#define DALVIK_TOKEN_JUMBO      (dalvik_keywords[20])
#define DALVIK_TOKEN_ENTER      (dalvik_keywords[21])
#define DALVIK_TOKEN_EXIT       (dalvik_keywords[22])
#define DALVIK_TOKEN_CAST       (dalvik_keywords[23])
#define DALVIK_TOKEN_OF         (dalvik_keywords[24])
#define DALVIK_TOKEN_LENGTH     (dalvik_keywords[25])
#define DALVIK_TOKEN_RANGE      (dalvik_keywords[26])
#define DALVIK_TOKEN_THROW      (dalvik_keywords[27])
#define DALVIK_TOKEN_GOTO       (dalvik_keywords[28])
#define DALVIK_TOKEN_PACKED     (dalvik_keywords[29])
#define DALVIK_TOKEN_SWITCH     (dalvik_keywords[30])
#define DALVIK_TOKEN_SPARSE     (dalvik_keywords[31])
#define DALVIK_TOKEN_CMPL       (dalvik_keywords[32])
#define DALVIK_TOKEN_CMPG       (dalvik_keywords[33])
#define DALVIK_TOKEN_CMP        (dalvik_keywords[34])
#define DALVIK_TOKEN_FLOAT      (dalvik_keywords[35])
#define DALVIK_TOKEN_DOUBLE     (dalvik_keywords[36])
#define DALVIK_TOKEN_LONG       (dalvik_keywords[37])
#define DALVIK_TOKEN_IF         (dalvik_keywords[38])
#define DALVIK_TOKEN_EQ         (dalvik_keywords[39])
#define DALVIK_TOKEN_NE         (dalvik_keywords[40])
#define DALVIK_TOKEN_LE         (dalvik_keywords[41])
#define DALVIK_TOKEN_GE         (dalvik_keywords[42])
#define DALVIK_TOKEN_GT         (dalvik_keywords[43])
#define DALVIK_TOKEN_LT         (dalvik_keywords[44])
#define DALVIK_TOKEN_EQZ        (dalvik_keywords[45])
#define DALVIK_TOKEN_NEZ        (dalvik_keywords[46])
#define DALVIK_TOKEN_LEZ        (dalvik_keywords[47])
#define DALVIK_TOKEN_GEZ        (dalvik_keywords[48])
#define DALVIK_TOKEN_GTZ        (dalvik_keywords[49])
#define DALVIK_TOKEN_LTZ        (dalvik_keywords[50])
#define DALVIK_TOKEN_BOOLEAN    (dalvik_keywords[51])
#define DALVIK_TOKEN_BYTE       (dalvik_keywords[52])
#define DALVIK_TOKEN_CHAR       (dalvik_keywords[53])
#define DALVIK_TOKEN_SHORT      (dalvik_keywords[54])
#define DALVIK_TOKEN_AGET       (dalvik_keywords[55])
#define DALVIK_TOKEN_APUT       (dalvik_keywords[56])
#define DALVIK_TOKEN_SGET       (dalvik_keywords[57])
#define DALVIK_TOKEN_SPUT       (dalvik_keywords[58])
#define DALVIK_TOKEN_IGET       (dalvik_keywords[59])
#define DALVIK_TOKEN_IPUT       (dalvik_keywords[60])
#define DALVIK_TOKEN_INVOKE     (dalvik_keywords[61])
#define DALVIK_TOKEN_VIRTUAL    (dalvik_keywords[62])
#define DALVIK_TOKEN_SUPER      (dalvik_keywords[63])
#define DALVIK_TOKEN_DIRECT     (dalvik_keywords[64])
#define DALVIK_TOKEN_STATIC     (dalvik_keywords[65])
#define DALVIK_TOKEN_INTERFACE  (dalvik_keywords[66])
#define DALVIK_TOKEN_INT        (dalvik_keywords[67])
#define DALVIK_TOKEN_TO         (dalvik_keywords[68])
#define DALVIK_TOKEN_NEG        (dalvik_keywords[69])
#define DALVIK_TOKEN_NOT        (dalvik_keywords[70])
#define DALVIK_TOKEN_ADD        (dalvik_keywords[71])
#define DALVIK_TOKEN_SUB        (dalvik_keywords[72])
#define DALVIK_TOKEN_MUL        (dalvik_keywords[73])
#define DALVIK_TOKEN_DIV        (dalvik_keywords[74])
#define DALVIK_TOKEN_REM        (dalvik_keywords[75])
#define DALVIK_TOKEN_AND        (dalvik_keywords[76])
#define DALVIK_TOKEN_OR         (dalvik_keywords[77])
#define DALVIK_TOKEN_XOR        (dalvik_keywords[78])
#define DALVIK_TOKEN_SHL        (dalvik_keywords[79])
#define DALVIK_TOKEN_SHR        (dalvik_keywords[80])
#define DALVIK_TOKEN_USHL       (dalvik_keywords[81])
#define DALVIK_TOKEN_USHR       (dalvik_keywords[82])
#define DALVIK_TOKEN_2ADDR      (dalvik_keywords[83])
#define DALVIK_TOKEN_LIT8       (dalvik_keywords[84])
#define DALVIK_TOKEN_LIT16      (dalvik_keywords[85])
#define DALVIK_TOKEN_NOP        (dalvik_keywords[86])
#define DALVIK_TOKEN_STRING     (dalvik_keywords[87])
#define DALVIK_TOKEN_DEFAULT    (dalvik_keywords[88])

int dalvik_tokens_init(void);

#endif
