#ifndef __CONSTANTS_H__
#define __CONSTANTS_H__

#ifndef DAVLIK_LABEL_POOL_SIZE
#   define DAVLIK_LABEL_POOL_SIZE 655217
#endif

#ifndef STRING_POOL_SIZE
#   define STRING_POOL_SIZE 100003
#endif

#ifndef DALVIK_POOL_INIT_SIZE
#   define DALVIK_POOL_INIT_SIZE 1024
#endif

#ifndef DALVIK_MAX_CATCH_BLOCK
#   define DALVIK_MAX_CATCH_BLOCK 1024
#endif

#endif
